server:
  port: 8090


spring:
  http:
    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

  datasource:
    url: jdbc:mysql://dleown.synology.me:8806/junggo
    username: junggo
    password: jgnaraDB1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

mybatis:
  type-aliases-package: com.project.together
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE


